### ISSUE TITLE
Looking this repo, is similar of what I did... 

### ISSUE THREAD

**Issue by Dracks** [xiusin/validator#1]
Looking at your validator stuff, seems similar to my library, maybe we can try to merge it? 

https://github.com/Dracks/vlang-validator-form

(I was thinking for a long time on splitting the parsing and the validator) 

I use mine to parse the form data in vweb, and parse the environment vars as a configuration object.

**Comment by xiusin** [comment]
@Dracks This is a module I extracted from v-system-skeleton and pushed it temporarily. A friend said he wanted to copy it or install it with vpm, so I simplified it and created a repository. Currently, it is very simple and many ideas and scenarios cannot be adapted. I will take some time to read your code, and it looks good.

**Comment by Dracks** [comment]
Mine is similar situation, which means, don't worry. I focused on the possibility to transform and validate data (but currently I don't support float) and I wished to provide something to only validate the struct, without transforming it.
